port: /dev/ttyDXL

joint_order: [left_back_coxa, left_back_femur, left_back_tibia,
              left_middle_coxa, left_middle_femur, left_middle_tibia,
              left_front_coxa, left_front_femur, left_front_tibia,
              right_front_coxa, right_front_femur, right_front_tibia,
              right_middle_coxa, right_middle_femur, right_middle_tibia,
              right_back_coxa, right_back_femur, right_back_tibia]

sleep_positions: [0, -1.57, 1.57, 0, -1.57, 1.57, 0, -1.57, 1.57,
                  0, -1.57, 1.57, 0, -1.57, 1.57, 0, -1.57, 1.57]

joint_state_publisher:
  update_rate: 30
  publish_states: true
  topic_name: joint_states

groups:
  left_back: [left_back_coxa, left_back_femur, left_back_tibia]
  left_middle: [left_middle_coxa, left_middle_femur, left_middle_tibia]
  left_front: [left_front_coxa, left_front_femur, left_front_tibia]
  right_front: [right_front_coxa, right_front_femur, right_front_tibia]
  right_middle: [right_middle_coxa, right_middle_femur, right_middle_tibia]
  right_back: [right_back_coxa, right_back_femur, right_back_tibia]

motors:
  left_back_coxa:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_back_femur:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_back_tibia:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_middle_coxa:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_middle_femur:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_middle_tibia:
    ID: 6
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_front_coxa:
    ID: 7
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_front_femur:
    ID: 8
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  left_front_tibia:
    ID: 9
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_front_coxa:
    ID: 10
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_front_femur:
    ID: 11
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_front_tibia:
    ID: 12
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_middle_coxa:
    ID: 13
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_middle_femur:
    ID: 14
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_middle_tibia:
    ID: 15
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_back_coxa:
    ID: 16
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_back_femur:
    ID: 17
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  right_back_tibia:
    ID: 18
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
