name: Question
description: Ask a question
title: "[Question]: "
labels: ["question", "crawlers"]
assignees:
  - LSInterbotix
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question here.
    validations:
      required: true
  - type: textarea
    id: robot_model
    attributes:
      label: Robot Model
      description: Which robot are you asking about (if any)?
      placeholder: pxmark4, wxmark4, etc.
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: Which operating system are you targeting when asking this question?
      multiple: true
      options:
        - Ubuntu 18.04
        - Ubuntu 20.04
        - Other (Describe in "Anything Else")
    validations:
      required: true
  - type: dropdown
    id: ros_version
    attributes:
      label: ROS Version
      description: Which version of ROS are you targeting when asking this question?
      multiple: true
      options:
        - ROS1 Melodic
        - ROS1 Noetic
        - Other (Describe in "Anything Else")
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything Else
      description: Please enter anything else you'd like to share here.
